schema_version: 1

context:
  name: mjviser
  version: "0.0.13"
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mujocolab/mjviser/archive/refs/tags/v${{ version }}.zip
  sha256: 9afacc53883842c289331cf66ffa031fe5f1781ed7930b53907d53ddd70aae0d

build:
  noarch: python
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mjviser = mjviser.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - mujoco >=3.6.0
    - numpy
    - trimesh >=4.8.3
    - viser >=1.0.26
    - pillow >=12.2.0

tests:
  - python:
      imports:
        - mjviser
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pytest tests/
    files:
      source:
        - pyproject.toml
        - tests/
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
        - nodeenv

about:
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/mujocolab/mjviser
  summary: Web-based MuJoCo viewer powered by Viser.

extra:
  recipe-maintainers:
    - diegoferigo
