#!/bin/bash
set -exo pipefail

if [[ "${mpi}" == "nompi" ]]; then
  OSPRAY_MPI=OFF
else
  OSPRAY_MPI=ON
fi

cmake -S . -B build -G Ninja \
    ${CMAKE_ARGS} \
    -DISPC_EXECUTABLE="${BUILD_PREFIX}/bin/ispc" \
    -DOSPRAY_MODULE_CPU=ON \
    -DOSPRAY_MODULE_GPU=OFF \
    -DOSPRAY_ENABLE_VOLUMES=ON \
    -DOSPRAY_MODULE_DENOISER=ON \
    -DOSPRAY_MODULE_MPI=${OSPRAY_MPI} \
    -DOSPRAY_ENABLE_APPS=ON \
    -DOSPRAY_ENABLE_APPS_TESTING=ON \
    -DOSPRAY_ENABLE_APPS_EXAMPLES=OFF \
    -DOSPRAY_ENABLE_APPS_TUTORIALS=OFF \
    -DOSPRAY_ENABLE_APPS_BENCHMARK=OFF \
    -DOSPRAY_INSTALL_DEPENDENCIES=OFF
cmake --build build --parallel ${CPU_COUNT}
cmake --install build
