@echo on
setlocal enabledelayedexpansion

set _LIBRARY=%LIBRARY_PREFIX:\=/%

if "%mpi%"=="impi" (
    set "OSPRAY_MPI=ON"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_C_ADDITIONAL_INCLUDE_DIRS:PATH=!_LIBRARY!/include"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_CXX_ADDITIONAL_INCLUDE_DIRS:PATH=!_LIBRARY!/include"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_C_LIB_NAMES=IMPI"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_CXX_LIB_NAMES=IMPI"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_IMPI_LIBRARY:PATH=!_LIBRARY!/lib/impi.lib"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_ASSUME_NO_BUILTIN_MPI=ON"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_SKIP_COMPILER_WRAPPER=ON"
    set "CMAKE_ARGS=!CMAKE_ARGS! -DMPI_SKIP_GUESSING=ON"
) else (
    set "OSPRAY_MPI=OFF"
)

cmake -S . -B build -G Ninja ^
    !CMAKE_ARGS! ^
    -DISPC_EXECUTABLE="%BUILD_PREFIX%\Library\bin\ispc.exe" ^
    -DOSPRAY_MODULE_CPU=ON ^
    -DOSPRAY_MODULE_GPU=OFF ^
    -DOSPRAY_ENABLE_VOLUMES=ON ^
    -DOSPRAY_MODULE_DENOISER=ON ^
    -DOSPRAY_MODULE_MPI=!OSPRAY_MPI! ^
    -DOSPRAY_ENABLE_APPS=ON ^
    -DOSPRAY_ENABLE_APPS_TESTING=OFF ^
    -DOSPRAY_ENABLE_APPS_EXAMPLES=OFF ^
    -DOSPRAY_ENABLE_APPS_TUTORIALS=ON ^
    -DOSPRAY_ENABLE_APPS_BENCHMARK=OFF ^
    -DOSPRAY_INSTALL_DEPENDENCIES=OFF
if %ERRORLEVEL% neq 0 exit /b 1

cmake --build build --parallel %CPU_COUNT%
if %ERRORLEVEL% neq 0 exit /b 1

cmake --install build
if %ERRORLEVEL% neq 0 exit /b 1
