schema_version: 1

context:
  version: "3.2.0"
  build_base: 0
  build: ${{ build_base + 100 if mpi == 'nompi' else build_base }}
  mpi_prefix: ${{ 'nompi' if mpi == 'nompi' else 'mpi_' + mpi }}

package:
  name: ospray
  version: ${{ version }}

source:
  url: https://github.com/RenderKit/ospray/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2c8108df2950bc5d1bc2a62f74629233dbe4f36e3f6a8ea032907d4a3fdc6750

build:
  number: ${{ build }}
  string: ${{ mpi_prefix }}_h${{ hash }}_${{ build }}

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ispc
    - ninja
  host:
    - if: mpi != "nompi"
      then:
        - ${{ mpi }}
        - snappy
    - embree
    - openimagedenoise
    - openvkl
    - rkcommon ==1.14.0
    - tbb-devel
  run_exports:
    - ${{ pin_subpackage("ospray", upper_bound="x.x") }}

tests:
  - package_contents:
      bin:
        - if: mpi == "nompi"
          then:
            - ospTutorial
            - ospTutorialCpp
            - ospTutorialAsync
          else:
            - ospMPIDistribTutorial
            - ospMPIDistribTutorialCpp
            - ospMPIDistribTutorialAsync
      include:
        - ospray/ospray.h
        - ospray/ospray_cpp.h
      lib:
        - ospray
        - if: mpi != "nompi"
          then:
            - ospray_mpi_common
            - ospray_module_mpi_offload
            - ospray_module_mpi_distributed_cpu
  - script:
      - if: unix
        then: |
          ospTutorial
          test -f firstFrame.ppm
          test -f accumulatedFrame.ppm
          rm -f firstFrame.ppm accumulatedFrame.ppm
          ospTutorialCpp
          test -f firstFrameCpp.ppm
          test -f accumulatedFrameCpp.ppm
      - if: win
        then: |
          ospTutorial
          if not exist firstFrame.ppm exit 1
          if not exist accumulatedFrame.ppm exit 1
          if exist firstFrame.ppm del firstFrame.ppm
          if exist accumulatedFrame.ppm del accumulatedFrame.ppm
          ospTutorialCpp
          if not exist firstFrameCpp.ppm exit 1
          if not exist accumulatedFrameCpp.ppm exit 1

about:
  homepage: https://www.ospray.org
  repository: https://github.com/RenderKit/OSPRay
  documentation: https://www.ospray.org/documentation.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: An Open, Scalable, Portable, Ray Tracing Based Rendering Engine for High-Fidelity Visualization
  description: |
    Intel® OSPRay is an open source, scalable, and portable ray tracing engine for high-performance,
    high-fidelity visualization on Intel Architecture CPUs, Intel Xe GPUs, and Aarch64/ARM64 CPUs.
    OSPRay is part of the Intel Rendering Toolkit (Render Kit) and is released under the permissive Apache 2.0 license.

    The purpose of OSPRay is to provide an open, powerful, and easy-to-use rendering library that allows one
    to easily build applications that use ray tracing based rendering for interactive applications
    (including both surface- and volume-based visualizations).
    OSPRay runs on anything from laptops, to workstations, to compute nodes in HPC systems.

extra:
  recipe-maintainers:
    - eunos-1128
