schema_version: 1

context:
  version: "3.2.0"

package:
  name: ospray
  version: ${{ version }}

source:
  url: https://github.com/RenderKit/ospray/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2c8108df2950bc5d1bc2a62f74629233dbe4f36e3f6a8ea032907d4a3fdc6750

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ispc
    - ninja
  host:
    - embree
    - gtest
    - openimagedenoise
    - openvkl
    - rkcommon
    - tbb-devel
  run_exports:
    - ${{ pin_subpackage("ospray", upper_bound="x.x") }}

about:
  homepage: https://www.ospray.org
  repository: https://github.com/RenderKit/OSPRay
  documentation: https://www.ospray.org/documentation.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: An Open, Scalable, Portable, Ray Tracing Based Rendering Engine for High-Fidelity Visualization
  description: |
    Intel® OSPRay is an open source, scalable, and portable ray tracing engine for high-performance,
    high-fidelity visualization on Intel Architecture CPUs, Intel Xe GPUs, and Aarch64/ARM64 CPUs.
    OSPRay is part of the Intel Rendering Toolkit (Render Kit) and is released under the permissive Apache 2.0 license.

    The purpose of OSPRay is to provide an open, powerful, and easy-to-use rendering library that allows one
    to easily build applications that use ray tracing based rendering for interactive applications
    (including both surface- and volume-based visualizations).
    OSPRay runs on anything from laptops, to workstations, to compute nodes in HPC systems.

tests:
  - package_contents:
      files:
        - lib/cmake/ospray-*/osprayConfig.cmake
        - lib/cmake/ospray-*/osprayConfigVersion.cmake
      include:
        - ospray/ospray.h
      lib:
        - ospray

  - script:
      - cmake -G Ninja -S test_image_data -B build_regression_tests -D OSPRAY_TEST_ISA=AVX2
      - cmake --build build_regression_tests --target ospray_test_data
      - cd build_regression_tests
      - mkdir failed
      - ospTestSuite --gtest_output=xml:tests.xml --baseline-dir=regression_test_baseline --failed-dir=failed
    files:
      source:
        - test_image_data/
    requirements:
      run:
        - ${{ compiler("cxx") }}
        - cmake
        - ninja

extra:
  recipe-maintainers:
    - eunos-1128
