context:
  version: "6.1.9"

package:
  name: ftxui
  version: ${{ version }}

source:
  url: https://github.com/ArthurSonzogni/FTXUI/releases/download/v${{ version }}/source.tar.gz
  sha256: 868670e451c38bdc3ad23d086796543cde4a845fd0420148b198dff5cbe08285

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  # We pin downstream consumers to the full patch version for now
  # because FTXUI 6.x does not yet provide ABI guarantees.
  # Once upstream introduces an SOVERSION/ABI policy (planned for 7.0.0), this can be relaxed to a
  # looser `upper_bound` tied to the SOVERSION.
  # See discussion: https://github.com/ArthurSonzogni/FTXUI/discussions/1249
  run_exports:
    - ${{ pin_subpackage("ftxui", upper_bound="x.x.x") }}

tests:
  - package_contents:
      include:
        - ftxui/**
      lib:
        - ftxui-component
        - ftxui-dom
        - ftxui-screen
  - script:
    - cmake-package-check ftxui --targets ftxui::dom ftxui::component ftxui::screen
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - cmake-package-check

about:
  homepage: https://github.com/ArthurSonzogni/FTXUI
  license: MIT
  license_file: LICENSE
  summary: "Flexible terminal user interface library for C++"

extra:
  recipe-maintainers:
    - RiccardoGrieco
