{% set version = "0.2.7" %}

package:
  name: page-dewarp
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/page-dewarp/page_dewarp-{{ version }}.tar.gz
  sha256: 4406c67845ee8789396d1b5ed264483a98aeb86ecaf9a02d8f5daf25d3a1fe73

build:
  entry_points:
    - page-dewarp = page_dewarp.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - msgspec >=0.18.6
    - numpy >1.25
    - jax >=0.6.2
    - opencv
    - scipy
    - sympy

test:
  imports:
    - page_dewarp
  commands:
    - pip check
    - page-dewarp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lmmx/page-dewarp
  summary: Page dewarping and thresholding using a cubic sheet model.
  doc_url: https://page-dewarp.vercel.app/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
    - danielopitz
