context:
  version: "5.0.0"

package:
  name: salt-terminal
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/salt/archive/v${{ version }}.tar.gz
  sha256: e934135c0b2fd8d967d5a1244490e179f64a7f22e2665ef26171752561997c23

build:
  number: 0
  # Remove windows in the future when we have windows support
  skip:
    - osx
    - win
  script: |
    set -exo pipefail
    cmake -S . -B build -G Ninja \
      ${CMAKE_ARGS} \
      -DBUILD_DOCUMENTATION=ON
    cmake --build build --parallel ${CPU_COUNT}
    ./build/salt -i --prefix ${PREFIX}

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - myst-parser
    - pkg-config
    - sphinx
  host:
    - asio
    - cryptopp
    - expat
    - freetype
    - glib
    - gtk4
    - libcanberra
    - libgxrio
    - libmcfp
    - libmgui
    - libpinch
    - libzeep
    - maartens_resource_compiler
    - zeem
    - zlib

tests:
  - script:
      - salt --version
      - salt --help

about:
  homepage: "https://forge.hekkelman.net/maarten/salt"
  summary: "Terminal with built-in SSH"
  description: Salt is a terminal emulator with built-in SSH.
  license: BSD-2-Clause
  license_file: LICENSE
  repository: https://forge.hekkelman.net/maarten/salt

extra:
  recipe-maintainers:
    - eunos-1128
