{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggscribe
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggscribe_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggscribe/ggscribe_{{ version }}.tar.gz
  sha256: f5495f9b6f7c218739e75d114f218a625c62f3038fc7c56c61b69b9624e2a6e1

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-farver
    - r-ggplot2 >=4.0.0
    - r-glue
    - r-rlang
    - r-scales
  run:
    - r-base
    - r-farver
    - r-ggplot2 >=4.0.0
    - r-glue
    - r-rlang
    - r-scales

test:
  commands:
    - $R -e "library('ggscribe')"           # [not win]
    - "\"%R%\" -e \"library('ggscribe')\""  # [win]

about:
  home: https://davidhodge931.github.io/ggscribe/
  dev_url: https://github.com/davidhodge931/ggscribe
  license: MIT
  summary: Annotation helper functions for publication-quality 'ggplot2' visualisation. These
    functions make it easier to annotate plots in a way that stays consistent with the
    set theme.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
