context:
  version: "0.6.1"

package:
  name: crysfml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/crysfml/crysfml-${{ version }}.tar.gz
  sha256: 078a0b788abebf98659d0902d61f213ca177879dd64e3b7fc6781a5b5654909f

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: match(python, "<3.11")

requirements:
  host:
    - ${{ compiler('fortran') }}
    - python
    - cmake
    - ninja
    - make
    - scikit-build-core >=0.11
    - versioningit
    - pip
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - crysfml
      pip_check: true

about:
  summary: Python access to the CrysFML2008 crystallographic Fortran library
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - repo/CFML/LICENSE
  homepage: https://pypi.org/project/crysfml/

extra:
  recipe-maintainers:
    - MridulS
