schema_version: 1

context:
  name: "grid-apps"
  version: "0.1.0"  # This will be replaced by the actual version in the build process
  python_min: "3.10"
  module_name: ${{ name|lower|replace("-", "_") }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.zip
  sha256: 642BE53F26562A67A54CDA00C59808BF4C55A2DB7EA5A09F04E0767CD843D094

build:
  number: 0
  noarch: python
  script: 
    - export POETRY_DYNAMIC_VERSIONING_BYPASS=${{ version }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    
requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, 1.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoh5py >=0.12.0, 0.12.*
    - geoapps-utils >=0.6.0, 0.6.*
    # other direct dependencies
    - discretize 0.11.*
    - numpy 1.26.*
    - pydantic >=2.5.2, 2.*
    - scipy 1.14.*

tests:
  - python:
      imports:
        - ${{ module_name }}
        - ${{ module_name }}._version
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/
  - package_contents:
      files:
        - site-packages/${{ module_name }}/_version.py

about:
  summary: Grid creation and manipulation using GEOH5 format.
  description: |
    The grid-apps package offers tools for the creation and manipulation of grid objects
    (Octree, BlockModel, Grid2D, DrapeModel) using various Python libraries
    and `geoh5py <https://mirageoscience-geoh5py.readthedocs-hosted.com/>`_.
  license: MIT
  license_file:
    - LICENSE
    - docs/source/THIRD_PARTY_SOFTWARE.rst
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/grid-apps

extra:
  recipe-maintainers:
    - conda-forge/geoh5py