context:
  version: "0.3.6"

package:
  name: cargo-leptos
  version: ${{ version }}

source:
  url: https://github.com/leptos-rs/cargo-leptos/releases/download/v${{ version }}/source.tar.gz
  sha256: deb8a9d77bfb28533137fa9400f0a2ad03892d6a6f858265b7548c9e6d0f805b

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
      # Use cmake to build aws-lc-sys, because conda's CFLAGS inject -O2 which
      # overrides the -O0 required by jitterentropy-base.c, causing a build failure.
      AWS_LC_SYS_CMAKE_BUILDER: "1"
      OPENSSL_NO_VENDOR: "1"
    content:
      - if: unix
        then:
          - export OPENSSL_DIR="$PREFIX"
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - set OPENSSL_DIR=%LIBRARY_PREFIX%
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
      - if: unix
        then:
          - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
          - $PREFIX/bin/cargo-leptos completions zsh > $PREFIX/share/zsh/site-functions/_cargo-leptos
          - $PREFIX/bin/cargo-leptos completions bash > $PREFIX/share/bash-completion/completions/cargo-leptos
          - $PREFIX/bin/cargo-leptos completions fish > $PREFIX/share/fish/vendor_completions.d/cargo-leptos.fish


requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - cmake
    - if: unix
      then: make
    - if: osx
      then: ld64
  host:
    - openssl

tests:
  - script: cargo-leptos --help
  - package_contents:
      bin:
        - cargo-leptos
      files:
        - if: unix
          then:
            - share/bash-completion/completions/cargo-leptos
            - share/fish/vendor_completions.d/cargo-leptos.fish
            - share/zsh/site-functions/_cargo-leptos
      strict: true

about:
  homepage: https://leptos.dev
  summary: 'Build tool for Leptos (Rust)'
  license: MIT
  license_file: LICENSE
  repository: https://github.com/leptos-rs/cargo-leptos

extra:
  recipe-maintainers:
    - maurosilber
