{% set version = '0.0.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-palette
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/palette_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/palette/palette_{{ version }}.tar.gz
  sha256: f5f778478af4316b8526cecf2382a6cd1aa02ad7367ed9a0eaf2a3341eca8d21

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-pillar
    - r-vctrs
  run:
    - r-base
    - r-cli
    - r-pillar
    - r-vctrs

test:
  commands:
    - $R -e "library('palette')"           # [not win]
    - "\"%R%\" -e \"library('palette')\""  # [win]

about:
  home: https://christophertkenny.com/palette/
  dev_url: https://github.com/christopherkenny/palette
  license: MIT
  summary: Hexadecimal codes are typically used to represent colors in R. Connecting these codes
    to their colors requires practice or memorization. 'palette' provides a 'vctrs'
    class for working with color palettes, including printing and plotting functions.
    The goal of the class is to place visual representations of color palettes directly
    on or, at least, next to their corresponding character representations. Palette
    extensions also are provided for data frames using 'pillar'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: palette
# Title: Color Scheme Helpers
# Version: 0.0.3
# Authors@R: person(given = "Christopher T.", family = "Kenny", role = c("aut", "cre"), email = "ctkenny@proton.me", comment = c(ORCID = "0000-0002-9386-6860"))
# Description: Hexadecimal codes are typically used to represent colors in R. Connecting these codes to their colors requires practice or memorization. 'palette' provides a 'vctrs' class for working with color palettes, including printing and plotting functions. The goal of the class is to place visual representations of color palettes directly on or, at least, next to their corresponding character representations. Palette extensions also are provided for data frames using 'pillar'.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# URL: https://github.com/christopherkenny/palette, https://christophertkenny.com/palette/
# BugReports: https://github.com/christopherkenny/palette/issues
# Imports: cli, pillar, vctrs
# Suggests: ggplot2, spelling, testthat (>= 3.0.0), vdiffr
# Config/testthat/edition: 3
# Language: en-US
# Depends: R (>= 4.1.0)
# NeedsCompilation: no
# Packaged: 2025-09-12 16:12:04 UTC; chris
# Author: Christopher T. Kenny [aut, cre] (ORCID: <https://orcid.org/0000-0002-9386-6860>)
# Maintainer: Christopher T. Kenny <ctkenny@proton.me>
# Repository: CRAN
# Date/Publication: 2025-09-13 05:10:29 UTC
