context:
  python_min: "3.9"
  version: "1.0.0"

package:
  name: jupyterlab-plugin-playground
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-plugin-playground/jupyterlab_plugin_playground-${{ version }}.tar.gz
  sha256: 13707d7bcab114618a33de50013f8991c25666a50c1cc62f23a5d9a0ffd58ec7

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5.dev0
    - pip
  run:
    - python >=${{ python_min }}
    - jupyterlab >=4.0,<5.dev0

tests:
  - python:
      imports:
        - jupyterlab_plugin_playground
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - jupyter labextension list
      - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/plugin-playground.*OK"
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyterlab/plugin-playground
  summary: A JupyterLab Plugin Playground.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MUFFANUJ
    - krassowski
